all:
  hosts:
    node1:
      ansible_host: 51.250.4.85
      ip: 10.5.0.17
      access_ip: 10.5.0.17
    node2:
      ansible_host: 84.252.143.77
      ip: 10.6.0.17
      access_ip: 10.6.0.17
    node3:
      ansible_host: 158.160.144.201
      ip: 10.7.0.7
      access_ip: 10.7.0.7
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
